language: node_js
node_js:
  - "4.2.3"
before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
script: gulp
after_script: ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage