language: node_js
node_js:
  - "4.2.3"
before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
script: gulp
before_install:
  - pip install codecov
after_success:
  - codecov